// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BackendApi.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NRP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peminjaman");
                });

            modelBuilder.Entity("BackendApi.Models.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fasilitas")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAktif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ruangan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fasilitas = "Proyektor, AC, Whiteboard",
                            IsAktif = true,
                            Kapasitas = 40,
                            Lokasi = "Gedung C Lantai 3",
                            NamaRuangan = "C-303"
                        },
                        new
                        {
                            Id = 2,
                            Fasilitas = "Proyektor, AC, Whiteboard, Sound System",
                            IsAktif = true,
                            Kapasitas = 35,
                            Lokasi = "Gedung B Lantai 1",
                            NamaRuangan = "B-104"
                        },
                        new
                        {
                            Id = 3,
                            Fasilitas = "Proyektor, AC, Whiteboard, Komputer",
                            IsAktif = true,
                            Kapasitas = 50,
                            Lokasi = "Gedung A Lantai 3",
                            NamaRuangan = "A-301"
                        });
                });

            modelBuilder.Entity("BackendApi.Models.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeminjamanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusBaru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusLama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalPerubahan")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
